- hosts: vpn
  become: yes
  tasks:
    - name: install openvpn server, easy-rsa
      apt:
        update_cache: yes
        name:
          - openvpn
          - easy-rsa

    - name: create server directories
      include_tasks: vpn/server-dirs.yml
      loop: "{{ servers }}"
      loop_control:
        loop_var: server

    - name: create easy-rsa vars
      include_tasks: vpn/server-rsa-vars.yml
      loop: "{{ servers }}"
      loop_control:
        loop_var: server

    - name: generate server rsa certificates
      include_tasks: vpn/server-rsa.yml
      loop: "{{ servers }}"
      loop_control:
        loop_var: server

    - name: create server configuration
      include_tasks: vpn/server-conf.yml
      loop: "{{ servers }}"
      loop_control:
        loop_var: server

    - name: create client configuration
      include_tasks: vpn/client-conf.yml
      loop: "{{ servers | product(clients) | list }}"
      loop_control:
        loop_var: serverclient

    - name: forward traffic via vpn
      block:
        - name: enable ip forward
          lineinfile:
            path: /proc/sys/net/ipv4/ip_forward
            line: '1'
            create: yes

        - name: persist ip forward
          lineinfile:
            path: /etc/sysctl.conf
            line: net.ipv4.ip_forward = 1
            create: yes

    - name: enable & start openvpn server service
      include_tasks: vpn/server-service.yml
      loop: "{{ servers }}"
      loop_control:
        loop_var: server

    - name: download client profile connection files
      include_tasks: vpn/client-download.yml
      loop: "{{ servers }}"
      loop_control:
        loop_var: server
